# Освобождаем P0.09 / P0.10 от NFC -> делаем обычными GPIO
CONFIG_NFCT_PINS_AS_GPIOS=y

# BLE и USB
CONFIG_ZMK_BLE=y
CONFIG_ZMK_USB=y

# Сон через 15 минут простоя
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Репорт уровня батареи. На SuperMini делителя нет — значения будут неточными.
# Если хочешь полностью убрать — поменяй =y на =n.
CONFIG_ZMK_BATTERY_REPORTING=y