# Правая половина как самостоятельная BLE/USB HID-клавиатура.
CONFIG_ZMK_KEYBOARD_NAME="Dactyl Right"

CONFIG_ZMK_BLE=y
CONFIG_ZMK_USB=y
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y